Agenzia Immobiliare: menus.c File Reference
menus.c File Reference
#include <stdio.h>
#include "menus.h"
#include "utils.h"
Functions
void mainMenu ()
int clientsMenu ()
int professMenu ()
int propertyMenu ()
Function Documentation
clientsMenu()
int clientsMenu ()
Definition at line 52 of file menus.c.
References clearScr(), and newLine().
Referenced by mainMenu().
mainMenu()
void mainMenu ()
Definition at line 13 of file menus.c.
References clearScr(), clientsMenu(), newLine(), professMenu(), and propertyMenu().
Referenced by main().
professMenu()
int professMenu ()
Definition at line 80 of file menus.c.
References clearScr(), and newLine().
Referenced by mainMenu().
propertyMenu()
int propertyMenu ()
Definition at line 108 of file menus.c.
References clearScr(), and newLine().
Referenced by mainMenu().