Agenzia Immobiliare: utils.h File Reference
utils.h File Reference
Data Structures
struct date
Functions
void newLine ()
void clearScr ()
Function Documentation
clearScr()
void clearScr ()
Definition at line 17 of file utils.c.
Referenced by clientsMenu(), mainMenu(), professMenu(), and propertyMenu().
newLine()
void newLine ()
Definition at line 12 of file utils.c.
Referenced by clientsMenu(), mainMenu(), professMenu(), and propertyMenu().